#!/bin/bash
set -x

DOMAIN=$1
DOMAIN_DATABASE_DIREC=$2

if [ $DOMAIN != "INDIA" ] && [ $DOMAIN != "USA" ] && [ $DOMAIN != "CA" ] && [ $DOMAIN != "UK" ]; then
	echo "No Such Domain"
	exit 1
fi

if ! [ 	-d $DOMAIN_DATABASE_DIREC ]; then
	echo "No Such Directory Exists"
	exit 1
fi

CURRENT_DIREC=$(pwd)
PROJECT_DIREC=$(pwd)/".."

LINK_SCRIPT_DIREC=$PROJECT_DIREC/"1.product_links"
METADATA_SCRIPT_DIREC=$PROJECT_DIREC/"2.product_metadata"
REVIEW_SCRIPT_DIREC=$PROJECT_DIREC/"3.reviews"

LINK_INDIA_SCRIPT=$LINK_SCRIPT_DIREC/"links_in.py"
LINK_USA_SCRIPT=$LINK_SCRIPT_DIREC/"links_com.py"
LINK_UK_SCRIPT=$LINK_SCRIPT_DIREC/"links_uk.py"
LINK_CA_SCRIPT=$LINK_SCRIPT_DIREC/"links_ca.py"

METADATA_INDIA_SCRIPT=$METADATA_SCRIPT_DIREC/"products_in.py"
METADATA_USA_SCRIPT=$METADATA_SCRIPT_DIREC/"products_com.py"
METADATA_UK_SCRIPT=$METADATA_SCRIPT_DIREC/"products_uk.py"
METADATA_CA_SCRIPT=$METADATA_SCRIPT_DIREC/"products_ca.py"

REVIEW_INDIA_SCRIPT=$REVIEW_SCRIPT_DIREC/"reviews_in.py"
REVIEW_USA_SCRIPT=$REVIEW_SCRIPT_DIREC/"reviews_com.py"
REVIEW_UK_SCRIPT=$REVIEW_SCRIPT_DIREC/"reviews_uk.py"
REVIEW_CA_SCRIPT=$REVIEW_SCRIPT_DIREC/"reviews_ca.py"

LOG_FILE_DIREC=$PROJECT_DIREC/"../log_files"

[ -d $LOG_FILE_DIREC ] || mkdir $LOG_FILE_DIREC

LOG_FILE_INDIA=$LOG_FILE_DIREC/"log_in.out"
LOG_FILE_USA=$LOG_FILE_DIREC/"log_com.out"
LOG_FILE_UK=$LOG_FILE_DIREC/"log_uk.out"
LOG_FILE_CA=$LOG_FILE_DIREC/"log_ca.out"

SHELL_SCRIPT_DIREC=$PROJECT_DIREC/"shell_scripts"

if [ $DOMAIN == "INDIA" ]; then
	python $LINK_INDIA_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_INDIA
	# python $METADATA_INDIA_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_INDIA &
	# python $REVIEW_INDIA_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_INDIA &
	wait

elif [ $DOMAIN == "USA" ]; then
	python $LINK_USA_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_USA
	# python $METADATA_USA_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_USA &
	# python $REVIEW_USA_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_USA &
	wait

elif [ $DOMAIN == "CA" ]; then
	python $LINK_CA_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_CA
	# python $METADATA_CA_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_CA &
	# python $REVIEW_CA_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_CA &
	wait

else
	python $LINK_UK_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_UK
	# python $METADATA_UK_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_UK &
	# python $REVIEW_UK_SCRIPT $DOMAIN_DATABASE_DIREC >> $LOG_FILE_UK &
	wait

fi

exit 0







